"""
Konfiguracja językowa - exempt words, set sizes, łączniki dla 8 języków Amazon.
"""

LANGUAGES = {
    "DE": {
        "name": "🇩🇪 Deutsch (Amazon.de)",
        "exempt_words": {
            "und", "oder", "der", "die", "das", "für", "mit", "auf", "in", "zu",
            "von", "aus", "bei", "am", "im", "als", "set", "cm", "er", "ein",
            "eine", "einen", "einer", "eines",
        },
        "set_sizes": {
            "1 szt.": "1 Stück", "2 szt.": "2er Set", "3 szt.": "3er Set",
            "4 szt.": "4er Set", "6 szt.": "6er Set", "8 szt.": "8er Set",
        },
        "connectors": {"for": "für", "from": "aus", "and": "und", "or": "oder"},
        "feature_adj": {
            "waschbar": "waschbare", "rutschfest": "rutschfeste",
            "wasserdicht": "wasserdichte", "wetterfest": "wetterfeste",
            "abnehmbar": "abnehmbare", "gesteppt": "gesteppte",
            "atmungsaktiv": "atmungsaktive",
        },
    },
    "FR": {
        "name": "🇫🇷 Français (Amazon.fr)",
        "exempt_words": {
            "et", "ou", "de", "du", "des", "le", "la", "les", "pour", "avec",
            "dans", "sur", "à", "en", "un", "une", "au", "aux", "par", "lot",
            "set", "cm",
        },
        "set_sizes": {
            "1 szt.": "1 Pièce", "2 szt.": "Lot de 2", "3 szt.": "Lot de 3",
            "4 szt.": "Lot de 4", "6 szt.": "Lot de 6", "8 szt.": "Lot de 8",
        },
        "connectors": {"for": "pour", "from": "en", "and": "et", "or": "ou"},
        "feature_adj": {
            "lavable": "lavable", "antidérapant": "antidérapant",
            "imperméable": "imperméable", "résistant": "résistant",
            "amovible": "amovible", "matelassé": "matelassé",
            "respirant": "respirant",
        },
    },
    "IT": {
        "name": "🇮🇹 Italiano (Amazon.it)",
        "exempt_words": {
            "e", "o", "di", "del", "della", "i", "le", "il", "lo", "la",
            "per", "con", "in", "su", "da", "a", "un", "una", "uno", "al",
            "alla", "set", "cm",
        },
        "set_sizes": {
            "1 szt.": "1 Pezzo", "2 szt.": "Set da 2", "3 szt.": "Set da 3",
            "4 szt.": "Set da 4", "6 szt.": "Set da 6", "8 szt.": "Set da 8",
        },
        "connectors": {"for": "per", "from": "in", "and": "e", "or": "o"},
        "feature_adj": {
            "lavabile": "lavabile", "antiscivolo": "antiscivolo",
            "impermeabile": "impermeabile", "resistente": "resistente",
            "rimovibile": "rimovibile", "trapuntato": "trapuntato",
            "traspirante": "traspirante",
        },
    },
    "ES": {
        "name": "🇪🇸 Español (Amazon.es)",
        "exempt_words": {
            "y", "o", "el", "la", "los", "las", "de", "del", "al", "para",
            "con", "en", "sobre", "por", "un", "una", "unos", "unas", "a",
            "set", "pack", "cm",
        },
        "set_sizes": {
            "1 szt.": "1 Pieza", "2 szt.": "Pack de 2", "3 szt.": "Pack de 3",
            "4 szt.": "Pack de 4", "6 szt.": "Pack de 6", "8 szt.": "Pack de 8",
        },
        "connectors": {"for": "para", "from": "en", "and": "y", "or": "o"},
        "feature_adj": {
            "lavable": "lavable", "antideslizante": "antideslizante",
            "impermeable": "impermeable", "resistente": "resistente",
            "extraíble": "extraíble", "acolchado": "acolchado",
            "transpirable": "transpirable",
        },
    },
    "NL": {
        "name": "🇳🇱 Nederlands (Amazon.nl)",
        "exempt_words": {
            "en", "of", "de", "het", "een", "voor", "met", "op", "in", "naar",
            "uit", "van", "bij", "aan", "om", "set", "cm",
        },
        "set_sizes": {
            "1 szt.": "1 Stuk", "2 szt.": "Set van 2", "3 szt.": "Set van 3",
            "4 szt.": "Set van 4", "6 szt.": "Set van 6", "8 szt.": "Set van 8",
        },
        "connectors": {"for": "voor", "from": "van", "and": "en", "or": "of"},
        "feature_adj": {
            "wasbaar": "wasbaar", "antislip": "antislip",
            "waterdicht": "waterdichte", "weerbestendig": "weerbestendig",
            "afneembaar": "afneembaar", "gewatteerd": "gewatteerd",
            "ademend": "ademend",
        },
    },
    "SE": {
        "name": "🇸🇪 Svenska (Amazon.se)",
        "exempt_words": {
            "och", "eller", "den", "det", "de", "en", "ett", "för", "med",
            "på", "i", "till", "från", "vid", "av", "set", "cm",
        },
        "set_sizes": {
            "1 szt.": "1 Styck", "2 szt.": "Set om 2", "3 szt.": "Set om 3",
            "4 szt.": "Set om 4", "6 szt.": "Set om 6", "8 szt.": "Set om 8",
        },
        "connectors": {"for": "för", "from": "av", "and": "och", "or": "eller"},
        "feature_adj": {
            "tvättbar": "tvättbar", "halkfri": "halkfri",
            "vattentät": "vattentät", "väderbeständig": "väderbeständig",
            "avtagbar": "avtagbar", "stickad": "stickad",
            "andningsbar": "andningsbar",
        },
    },
    "EN": {
        "name": "🇬🇧 English (Amazon.co.uk)",
        "exempt_words": {
            "and", "or", "the", "a", "an", "for", "with", "on", "in", "to",
            "from", "by", "at", "as", "of", "set", "pack", "cm",
        },
        "set_sizes": {
            "1 szt.": "1 Piece", "2 szt.": "Set of 2", "3 szt.": "Set of 3",
            "4 szt.": "Set of 4", "6 szt.": "Set of 6", "8 szt.": "Set of 8",
        },
        "connectors": {"for": "for", "from": "from", "and": "and", "or": "or"},
        "feature_adj": {
            "washable": "washable", "non-slip": "non-slip",
            "waterproof": "waterproof", "weatherproof": "weatherproof",
            "removable": "removable", "quilted": "quilted",
            "breathable": "breathable",
        },
    },
    "PL": {
        "name": "🇵🇱 Polski (Amazon.pl)",
        "exempt_words": {
            "i", "lub", "do", "dla", "z", "na", "w", "o", "przy", "przed",
            "za", "pod", "nad", "od", "ze", "set", "zestaw", "cm",
        },
        "set_sizes": {
            "1 szt.": "1 Sztuka", "2 szt.": "Zestaw 2 szt.",
            "3 szt.": "Zestaw 3 szt.", "4 szt.": "Zestaw 4 szt.",
            "6 szt.": "Zestaw 6 szt.", "8 szt.": "Zestaw 8 szt.",
        },
        "connectors": {"for": "do", "from": "z", "and": "i", "or": "lub"},
        "feature_adj": {
            "do prania": "do prania", "antypoślizgowy": "antypoślizgowy",
            "wodoodporny": "wodoodporny", "odporny na warunki": "odporny na warunki",
            "zdejmowany": "zdejmowany", "pikowany": "pikowany",
            "oddychający": "oddychający",
        },
    },
}

# Słownik tłumaczeń popularnych słów z branży home & garden (Amazon)
# Klucz: niemieckie słowo, Wartość: {kod_języka: tłumaczenie}
TRANSLATIONS = {
    # Produkty - kissen/poduszki
    "Sitzkissen": {"FR": "Coussin", "IT": "Cuscino", "ES": "Cojín",
                   "NL": "Zitkussen", "SE": "Sittkudde", "EN": "Seat Cushion",
                   "PL": "Poduszka"},
    "Stuhlkissen": {"FR": "Coussin de Chaise", "IT": "Cuscino Sedia",
                    "ES": "Cojín de Silla", "NL": "Stoelkussen",
                    "SE": "Stolskudde", "EN": "Chair Cushion",
                    "PL": "Poduszka na Krzesło"},
    "Bodenkissen": {"FR": "Coussin de Sol", "IT": "Cuscino da Pavimento",
                    "ES": "Cojín de Suelo", "NL": "Vloerkussen",
                    "SE": "Golvkudde", "EN": "Floor Cushion",
                    "PL": "Poduszka Podłogowa"},
    "Sitzpolster": {"FR": "Coussin", "IT": "Imbottitura",
                    "ES": "Almohadilla", "NL": "Zitkussen",
                    "SE": "Sittdyna", "EN": "Seat Pad", "PL": "Siedzisko"},
    "Stuhlauflage": {"FR": "Galette de Chaise", "IT": "Coprisedia",
                     "ES": "Cubreasiento", "NL": "Stoelmat",
                     "SE": "Stolsöverdrag", "EN": "Chair Pad",
                     "PL": "Nakładka na Krzesło"},
    "Palettenkissen": {"FR": "Coussin de Palette", "IT": "Cuscino per Pallet",
                       "ES": "Cojín de Palet", "NL": "Palletkussen",
                       "SE": "Pallkudde", "EN": "Pallet Cushion",
                       "PL": "Poduszka na Paletę"},
    "Palettenauflagen": {"FR": "Coussinets de Palette",
                         "IT": "Imbottitura per Pallet",
                         "ES": "Almohadillas de Palet",
                         "NL": "Palletoplegging", "SE": "Palldyna",
                         "EN": "Pallet Pads", "PL": "Nakładki na Paletę"},
    "Palettenpolster": {"FR": "Rembourrage de Palette",
                        "IT": "Imbottitura Pallet",
                        "ES": "Acolchado de Palet", "NL": "Palletvulling",
                        "SE": "Pallstoppning", "EN": "Pallet Padding",
                        "PL": "Wyściółka na Paletę"},
    "Palettensofa": {"FR": "Canapé Palette", "IT": "Divano Pallet",
                     "ES": "Sofá de Palet", "NL": "Pallet Bank",
                     "SE": "Pallsoffa", "EN": "Pallet Sofa",
                     "PL": "Sofa z Palet"},
    "Palettenmöbel": {"FR": "Meubles en Palette", "IT": "Mobili in Pallet",
                      "ES": "Muebles de Palet", "NL": "Palletmeubelen",
                      "SE": "Pallmöbler", "EN": "Pallet Furniture",
                      "PL": "Meble z Palet"},
    "Rückenlehne": {"FR": "Dossier", "IT": "Schienale", "ES": "Respaldo",
                    "NL": "Rugleuning", "SE": "Ryggstöd", "EN": "Backrest",
                    "PL": "Oparcie"},
    "Kissen": {"FR": "Coussin", "IT": "Cuscino", "ES": "Cojín",
               "NL": "Kussen", "SE": "Kudde", "EN": "Cushion",
               "PL": "Poduszka"},
    "Polster": {"FR": "Rembourrage", "IT": "Imbottitura", "ES": "Almohadilla",
                "NL": "Kussen", "SE": "Dyna", "EN": "Padding",
                "PL": "Polster"},
    "Auflage": {"FR": "Coussin", "IT": "Cuscino", "ES": "Cojín",
                "NL": "Kussen", "SE": "Dyna", "EN": "Pad",
                "PL": "Nakładka"},
    "Sofa": {"FR": "Canapé", "IT": "Divano", "ES": "Sofá", "NL": "Sofa",
             "SE": "Soffa", "EN": "Sofa", "PL": "Sofa"},

    # Kształty
    "Rund": {"FR": "Rond", "IT": "Rotondo", "ES": "Redondo", "NL": "Rond",
             "SE": "Rund", "EN": "Round", "PL": "Okrągły"},
    "Eckig": {"FR": "Carré", "IT": "Quadrato", "ES": "Cuadrado",
              "NL": "Vierkant", "SE": "Fyrkantig", "EN": "Square",
              "PL": "Kwadratowy"},
    "Quadrat": {"FR": "Carré", "IT": "Quadrato", "ES": "Cuadrado",
                "NL": "Vierkant", "SE": "Fyrkantig", "EN": "Square",
                "PL": "Kwadrat"},
    "Quadratisch": {"FR": "Carré", "IT": "Quadrato", "ES": "Cuadrado",
                    "NL": "Vierkant", "SE": "Fyrkantig", "EN": "Square",
                    "PL": "Kwadratowy"},
    "Rechteckig": {"FR": "Rectangulaire", "IT": "Rettangolare",
                   "ES": "Rectangular", "NL": "Rechthoekig",
                   "SE": "Rektangulär", "EN": "Rectangular",
                   "PL": "Prostokątny"},
    "Oval": {"FR": "Ovale", "IT": "Ovale", "ES": "Ovalado", "NL": "Ovaal",
             "SE": "Oval", "EN": "Oval", "PL": "Owalny"},

    # Materiały
    "Cord": {"FR": "Velours Côtelé", "IT": "Velluto a Coste",
             "ES": "Pana", "NL": "Corduroy", "SE": "Manchester",
             "EN": "Corduroy", "PL": "Sztruks"},
    "Filz": {"FR": "Feutre", "IT": "Feltro", "ES": "Fieltro", "NL": "Vilt",
             "SE": "Filt", "EN": "Felt", "PL": "Filc"},
    "Baumwolle": {"FR": "Coton", "IT": "Cotone", "ES": "Algodón",
                  "NL": "Katoen", "SE": "Bomull", "EN": "Cotton",
                  "PL": "Bawełna"},
    "Polyester": {"FR": "Polyester", "IT": "Poliestere", "ES": "Poliéster",
                  "NL": "Polyester", "SE": "Polyester", "EN": "Polyester",
                  "PL": "Poliester"},
    "Schaumstoff": {"FR": "Mousse", "IT": "Schiuma", "ES": "Espuma",
                    "NL": "Schuim", "SE": "Skum", "EN": "Foam",
                    "PL": "Pianka"},
    "Memory Foam": {"FR": "Mousse à Mémoire", "IT": "Memory Foam",
                    "ES": "Espuma Viscoelástica", "NL": "Traagschuim",
                    "SE": "Memory Foam", "EN": "Memory Foam",
                    "PL": "Pianka Pamięciowa"},
    "Leinen": {"FR": "Lin", "IT": "Lino", "ES": "Lino", "NL": "Linnen",
               "SE": "Linne", "EN": "Linen", "PL": "Len"},

    # Kolory
    "Anthrazit": {"FR": "Anthracite", "IT": "Antracite", "ES": "Antracita",
                  "NL": "Antraciet", "SE": "Antracit", "EN": "Anthracite",
                  "PL": "Antracyt"},
    "Grau": {"FR": "Gris", "IT": "Grigio", "ES": "Gris", "NL": "Grijs",
             "SE": "Grå", "EN": "Grey", "PL": "Szary"},
    "Hellgrau": {"FR": "Gris Clair", "IT": "Grigio Chiaro",
                 "ES": "Gris Claro", "NL": "Lichtgrijs", "SE": "Ljusgrå",
                 "EN": "Light Grey", "PL": "Jasnoszary"},
    "Dunkelgrau": {"FR": "Gris Foncé", "IT": "Grigio Scuro",
                   "ES": "Gris Oscuro", "NL": "Donkergrijs",
                   "SE": "Mörkgrå", "EN": "Dark Grey", "PL": "Ciemnoszary"},
    "Beige": {"FR": "Beige", "IT": "Beige", "ES": "Beige", "NL": "Beige",
              "SE": "Beige", "EN": "Beige", "PL": "Beżowy"},
    "Schwarz": {"FR": "Noir", "IT": "Nero", "ES": "Negro", "NL": "Zwart",
                "SE": "Svart", "EN": "Black", "PL": "Czarny"},
    "Weiß": {"FR": "Blanc", "IT": "Bianco", "ES": "Blanco", "NL": "Wit",
             "SE": "Vit", "EN": "White", "PL": "Biały"},
    "Braun": {"FR": "Marron", "IT": "Marrone", "ES": "Marrón", "NL": "Bruin",
              "SE": "Brun", "EN": "Brown", "PL": "Brązowy"},
    "Rot": {"FR": "Rouge", "IT": "Rosso", "ES": "Rojo", "NL": "Rood",
            "SE": "Röd", "EN": "Red", "PL": "Czerwony"},
    "Blau": {"FR": "Bleu", "IT": "Blu", "ES": "Azul", "NL": "Blauw",
             "SE": "Blå", "EN": "Blue", "PL": "Niebieski"},
    "Grün": {"FR": "Vert", "IT": "Verde", "ES": "Verde", "NL": "Groen",
             "SE": "Grön", "EN": "Green", "PL": "Zielony"},
    "Gelb": {"FR": "Jaune", "IT": "Giallo", "ES": "Amarillo", "NL": "Geel",
             "SE": "Gul", "EN": "Yellow", "PL": "Żółty"},
    "Cremeweiß": {"FR": "Crème", "IT": "Crema", "ES": "Crema",
                  "NL": "Crèmewit", "SE": "Krämvit", "EN": "Cream",
                  "PL": "Kremowy"},

    # Cechy
    "waschbar": {"FR": "lavable", "IT": "lavabile", "ES": "lavable",
                 "NL": "wasbaar", "SE": "tvättbar", "EN": "washable",
                 "PL": "do prania"},
    "rutschfest": {"FR": "antidérapant", "IT": "antiscivolo",
                   "ES": "antideslizante", "NL": "antislip",
                   "SE": "halkfri", "EN": "non-slip",
                   "PL": "antypoślizgowy"},
    "wasserdicht": {"FR": "imperméable", "IT": "impermeabile",
                    "ES": "impermeable", "NL": "waterdicht",
                    "SE": "vattentät", "EN": "waterproof",
                    "PL": "wodoodporny"},
    "wetterfest": {"FR": "résistant aux intempéries", "IT": "resistente",
                   "ES": "resistente al clima", "NL": "weerbestendig",
                   "SE": "väderbeständig", "EN": "weatherproof",
                   "PL": "odporny na warunki"},
    "abnehmbar": {"FR": "amovible", "IT": "rimovibile", "ES": "extraíble",
                  "NL": "afneembaar", "SE": "avtagbar", "EN": "removable",
                  "PL": "zdejmowany"},
    "gesteppt": {"FR": "matelassé", "IT": "trapuntato", "ES": "acolchado",
                 "NL": "gewatteerd", "SE": "stickad", "EN": "quilted",
                 "PL": "pikowany"},
    "atmungsaktiv": {"FR": "respirant", "IT": "traspirante",
                     "ES": "transpirable", "NL": "ademend",
                     "SE": "andningsbar", "EN": "breathable",
                     "PL": "oddychający"},

    # Konteksty - miejsca
    "Esszimmer": {"FR": "Salle à Manger", "IT": "Sala da Pranzo",
                  "ES": "Comedor", "NL": "Eetkamer", "SE": "Matsal",
                  "EN": "Dining Room", "PL": "Jadalnia"},
    "Wohnzimmer": {"FR": "Salon", "IT": "Soggiorno", "ES": "Salón",
                   "NL": "Woonkamer", "SE": "Vardagsrum",
                   "EN": "Living Room", "PL": "Salon"},
    "Schlafzimmer": {"FR": "Chambre", "IT": "Camera da Letto",
                     "ES": "Dormitorio", "NL": "Slaapkamer",
                     "SE": "Sovrum", "EN": "Bedroom", "PL": "Sypialnia"},
    "Küche": {"FR": "Cuisine", "IT": "Cucina", "ES": "Cocina",
              "NL": "Keuken", "SE": "Kök", "EN": "Kitchen",
              "PL": "Kuchnia"},
    "Garten": {"FR": "Jardin", "IT": "Giardino", "ES": "Jardín",
               "NL": "Tuin", "SE": "Trädgård", "EN": "Garden",
               "PL": "Ogród"},
    "Balkon": {"FR": "Balcon", "IT": "Balcone", "ES": "Balcón",
               "NL": "Balkon", "SE": "Balkong", "EN": "Balcony",
               "PL": "Balkon"},
    "Terrasse": {"FR": "Terrasse", "IT": "Terrazzo", "ES": "Terraza",
                 "NL": "Terras", "SE": "Terrass", "EN": "Patio",
                 "PL": "Taras"},
    "Büro": {"FR": "Bureau", "IT": "Ufficio", "ES": "Oficina",
             "NL": "Kantoor", "SE": "Kontor", "EN": "Office",
             "PL": "Biuro"},
    "Konferenzraum": {"FR": "Salle de Conférence",
                      "IT": "Sala Conferenze", "ES": "Sala de Conferencias",
                      "NL": "Vergaderzaal", "SE": "Konferensrum",
                      "EN": "Conference Room", "PL": "Sala Konferencyjna"},
    "Indoor": {"FR": "Intérieur", "IT": "Interno", "ES": "Interior",
               "NL": "Binnen", "SE": "Inomhus", "EN": "Indoor",
               "PL": "Wewnątrz"},
    "Outdoor": {"FR": "Extérieur", "IT": "Esterno", "ES": "Exterior",
                "NL": "Buiten", "SE": "Utomhus", "EN": "Outdoor",
                "PL": "Na Zewnątrz"},

    # Meble / typy
    "Stuhl": {"FR": "Chaise", "IT": "Sedia", "ES": "Silla", "NL": "Stoel",
              "SE": "Stol", "EN": "Chair", "PL": "Krzesło"},
    "Bank": {"FR": "Banc", "IT": "Panca", "ES": "Banco", "NL": "Bank",
             "SE": "Bänk", "EN": "Bench", "PL": "Ławka"},
    "Sitzbank": {"FR": "Banquette", "IT": "Panchina", "ES": "Banqueta",
                 "NL": "Zitbank", "SE": "Sittbänk", "EN": "Bench Seat",
                 "PL": "Ławka"},
    "Hocker": {"FR": "Tabouret", "IT": "Sgabello", "ES": "Taburete",
               "NL": "Kruk", "SE": "Pall", "EN": "Stool",
               "PL": "Taboret"},
    "Bürostuhl": {"FR": "Chaise de Bureau", "IT": "Sedia da Ufficio",
                  "ES": "Silla de Oficina", "NL": "Bureaustoel",
                  "SE": "Kontorsstol", "EN": "Office Chair",
                  "PL": "Krzesło Biurowe"},
    "Europaletten": {"FR": "Palettes Europe", "IT": "Pallet Europei",
                     "ES": "Palets Europeos", "NL": "Europallets",
                     "SE": "Europallar", "EN": "Euro Pallets",
                     "PL": "Europalety"},
    "Europalette": {"FR": "Palette Europe", "IT": "Pallet Europeo",
                    "ES": "Palet Europeo", "NL": "Europallet",
                    "SE": "Europall", "EN": "Euro Pallet",
                    "PL": "Europaleta"},
}


# Kategoryzacja słów - klucz = niemieckie słowo, wartość = kategoria
# Używane do auto-wyciągania danych z tytułów konkurencji
CATEGORIES = {
    # Produkty główne (mogą być main_kw lub synonimem)
    "Sitzkissen": "product", "Stuhlkissen": "product", "Bodenkissen": "product",
    "Sitzpolster": "product", "Stuhlauflage": "product", "Palettenkissen": "product",
    "Palettenauflagen": "product", "Palettenpolster": "product",
    "Palettensofa": "product", "Palettenmöbel": "product", "Rückenlehne": "product",
    "Kissen": "product", "Polster": "product", "Auflage": "product", "Sofa": "product",

    # Kształty
    "Rund": "shape", "Eckig": "shape", "Quadrat": "shape", "Quadratisch": "shape",
    "Rechteckig": "shape", "Oval": "shape",

    # Materiały
    "Cord": "material", "Filz": "material", "Baumwolle": "material",
    "Polyester": "material", "Schaumstoff": "material", "Memory Foam": "material",
    "Leinen": "material",

    # Kolory
    "Anthrazit": "color", "Grau": "color", "Hellgrau": "color", "Dunkelgrau": "color",
    "Beige": "color", "Schwarz": "color", "Weiß": "color", "Braun": "color",
    "Rot": "color", "Blau": "color", "Grün": "color", "Gelb": "color",
    "Cremeweiß": "color",

    # Cechy
    "waschbar": "feature", "rutschfest": "feature", "wasserdicht": "feature",
    "wetterfest": "feature", "abnehmbar": "feature", "gesteppt": "feature",
    "atmungsaktiv": "feature",

    # Konteksty (gdzie używać produktu)
    "Esszimmer": "context", "Wohnzimmer": "context", "Schlafzimmer": "context",
    "Küche": "context", "Garten": "context", "Balkon": "context",
    "Terrasse": "context", "Büro": "context", "Konferenzraum": "context",
    "Indoor": "context", "Outdoor": "context",

    # Meble (na czym się używa - też kontekst, ale meble)
    "Stuhl": "context", "Bank": "context", "Sitzbank": "context",
    "Hocker": "context", "Bürostuhl": "context",
    "Europaletten": "context", "Europalette": "context",
}
